name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get Tagged Version
      id: latest_tag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0
    - uses: apexskier/github-semver-parse@v1
      id: semver
      with:
        version: ${{ steps.latest_tag.outputs.tag }}
    - name: Get the output
      run: echo "The output was ${{ steps.semver.outputs.minor }}"
