name: Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  revision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Tagged Version
        id: latest_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0
    outputs:
      number: '[${{ steps.latest_tag.outputs.tag }},)'

  build:
    needs: revision
    runs-on: ubuntu-latest
    steps:
    - name: Print current and next version
      run: |
        echo "Revision: ${{ needs.revision.outputs.number }}"

