name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get Tagged Version
      id: latest_tag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0
    - name: Parse semver string
      id: semver 
      uses: booxmedialtd/ws-action-parse-semver@v1
      with:
        input_string: ${{ steps.latest_tag.outputs.tag }}
    - name: Use parsed semver
      run: |
          echo "v${{ steps.semver_parser.outputs.major }}"
          echo "v${{ steps.semver_parser.outputs.minor }}"
          echo "v${{ steps.semver_parser.outputs.patch }}"
          echo "v${{ steps.semver_parser.outputs.prerelease }}"
          echo "v${{ steps.semver_parser.outputs.build }}"
          echo "v${{ steps.semver_parser.outputs.fullversion }}"
