name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get Tagged Version
      id: latest_tag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0
    - uses: rickstaa/action-get-semver@v1
      id: semver
      with:
        bump_level: "minor"
    - name: Print current and next version
      run: |
        echo "Current version: ${{ steps.semver.outputs.current_version  }}"
        echo "Next version: ${{ steps.semver.outputs.next_version }}"