name: Test

on:
  push:
    branches:
      - master
    tags:
      - '*'
  workflow_dispatch:

env:
  CACHE_PREFIX: mscore-pr-maven-

jobs:

  revision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Tagged Version
        id: latest_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0
    outputs:
      number: '[${{ steps.latest_tag.outputs.tag }},)'

  build:
    needs: revision
    runs-on: ubuntu-latest
    steps:
    - name: Print version
      run: |
        echo "Revision: ${{ needs.revision.outputs.number }}"
    - name: Print event context
      run: |
        echo "Github context: ${{ toJson(github) }}"
    - name: Print reference type branch
      if: ${{ github.ref_type }} == 'branch'
      run: |
        echo "Event name: ${{ github.ref_type }}"
    - name: Print event name type branch
      if: github.ref_type == 'tag'
      run: |
        echo "Event name: ${{ github.event_name }}"
    - name: Print docker
      run: |
        docker info
    - name: pwd
      run: pwd
    - name: cd
      run: cd .github/workflows
    - name: pwd
      run: pwd

